name = "SMin"
license = "MIT"
licenselink = "https://github.com/goodroot/hugo-smin/blob/master/LICENSE.md"
description = "A sort-of minimal theme. Based off the eXtremely minimal theme by Yihui Xui."
homepage = "https://goodroot.ca"
tags = ["minimal", "blog", "personal", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.01"

[author]
  name = "Kellen Evan Person"
  homepage = "https://goodroot.ca"
