baseurl = "/"
languageCode = "en-us"
title = "Classic"
theme = "hugo-classic"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.feed]]
    name = "RSS"
    url = "/index.xml"

[params]
    description = "A simple, minimal blog with a fixed header."
    footer = "Open-Source | [Github](https://github.com/goodroot/hugo-classic) | [Twitter](https://twitter.com/thegoodroot)"
